[package]
edition = "2021"
name = "basic_video_player"
version = "0.1.0"

[dependencies]
iced_video.workspace = true

[dependencies.iced]
features = ["tokio", "debug", "image", "svg", "canvas"]
workspace = true
